language: python
python:
  - "2.7"
install:
  - "pip install -r requirements.txt"
  - "pip install coverage"
  - "pip install coveralls"
script: coverage run -m unittest discover -s monitorrent/tests -p *_tests.py
after_success: coveralls